package dev.kdb.jdbc

import dev.kdb.sql.SqlParameter
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.SQLFeatureNotSupportedException
import java.sql.SQLWarning
import java.sql.Statement

open class KdbStatement(
    private val connection: KdbSqlConnection,
) : Statement {
    private var closed = false
    private var maxRows = 0
    private var queryTimeout = 0

    override fun executeQuery(sql: String): ResultSet = executeQuery(sql, emptyList())

    internal fun executeQuery(
        sql: String,
        parameters: List<SqlParameter>,
    ): ResultSet {
        checkOpen()
        val normalized = qualifyTable(sql)
        val result = connection.blocking { connection.executeHybrid(normalized, parameters) }
        return queryResultSet(result.result)
    }

    override fun execute(sql: String): Boolean {
        val upper = sql.trimStart().uppercase()
        return if (upper.startsWith("SELECT")) {
            executeQuery(sql)
            true
        } else {
            connection.checkWritable()
            connection.blocking { connection.executeHybrid(qualifyTable(sql), emptyList()) }
            false
        }
    }

    override fun executeUpdate(sql: String): Int = executeUpdate(sql, emptyList())

    internal fun executeUpdate(
        sql: String,
        parameters: List<SqlParameter>,
    ): Int {
        connection.checkWritable()
        val result = connection.blocking { connection.executeHybrid(qualifyTable(sql), parameters) }
        return result.result.rowsAffected
    }

    internal fun execute(
        sql: String,
        parameters: List<SqlParameter>,
    ): Boolean {
        val upper = sql.trimStart().uppercase()
        return if (upper.startsWith("SELECT")) {
            executeQuery(sql, parameters)
            true
        } else {
            connection.checkWritable()
            connection.blocking { connection.executeHybrid(qualifyTable(sql), parameters) }
            false
        }
    }

    override fun getConnection(): Connection = connection as Connection

    override fun close() {
        closed = true
    }

    override fun isClosed(): Boolean = closed

    override fun getMaxRows(): Int = maxRows

    override fun setMaxRows(max: Int) {
        maxRows = max
    }

    override fun getQueryTimeout(): Int = queryTimeout

    override fun setQueryTimeout(seconds: Int) {
        queryTimeout = seconds
    }

    override fun getWarnings(): SQLWarning? = null

    override fun clearWarnings() {}

    override fun cancel() {}

    override fun setCursorName(name: String?) {}

    override fun setFetchDirection(direction: Int) {}

    override fun getFetchDirection(): Int = ResultSet.FETCH_FORWARD

    override fun setFetchSize(rows: Int) {}

    override fun getFetchSize(): Int = 0

    override fun getResultSetType(): Int = ResultSet.TYPE_FORWARD_ONLY

    override fun getResultSetConcurrency(): Int = ResultSet.CONCUR_READ_ONLY

    override fun getResultSetHoldability(): Int = ResultSet.HOLD_CURSORS_OVER_COMMIT

    override fun getMoreResults(): Boolean = false

    override fun getMoreResults(current: Int): Boolean = false

    override fun getGeneratedKeys(): ResultSet = throw SQLFeatureNotSupportedException()

    override fun getResultSet(): ResultSet? = null

    override fun getUpdateCount(): Int = -1

    override fun setEscapeProcessing(enable: Boolean) {}

    override fun getMaxFieldSize(): Int = 0

    override fun setMaxFieldSize(max: Int) {}

    override fun setPoolable(poolable: Boolean) {}

    override fun isPoolable(): Boolean = false

    override fun closeOnCompletion() {}

    override fun isCloseOnCompletion(): Boolean = false

    override fun <T> unwrap(iface: Class<T>): T = throw SQLFeatureNotSupportedException()

    override fun isWrapperFor(iface: Class<*>): Boolean = false

    override fun execute(
        sql: String,
        autoGeneratedKeys: Int,
    ): Boolean = execute(sql)

    override fun execute(
        sql: String,
        columnIndexes: IntArray?,
    ): Boolean = execute(sql)

    override fun execute(
        sql: String,
        columnNames: Array<out String>?,
    ): Boolean = execute(sql)

    override fun executeUpdate(
        sql: String,
        autoGeneratedKeys: Int,
    ): Int = executeUpdate(sql)

    override fun executeUpdate(
        sql: String,
        columnIndexes: IntArray?,
    ): Int = executeUpdate(sql)

    override fun executeUpdate(
        sql: String,
        columnNames: Array<out String>?,
    ): Int = executeUpdate(sql)

    override fun addBatch(sql: String?) {}

    override fun clearBatch() {}

    override fun executeBatch(): IntArray = throw SQLFeatureNotSupportedException()

    protected fun checkOpen() {
        if (closed) throw SQLException("Statement is closed")
    }

    /** SQL table names stay short (e.g. `users`); namespace comes from [KdbSqlConnection] context. */
    private fun qualifyTable(sql: String): String = sql
}
